import streamlit as st

from crew.research_crew import run_research_crew
from agents.clarification_agent import needs_clarification
from memory import save_memory, get_memory, get_last_report, clear_memory


st.set_page_config(
    page_title="Agentic Research Analyst",
    layout="wide"
)

st.title("Agentic Research Analyst")

# session initiate
# restore last report from persistent memory so
# follow-up context survives page refresh
if "last_report" not in st.session_state:
    st.session_state.last_report = get_last_report()
if "last_query" not in st.session_state:
    st.session_state.last_query = ""
if "last_plan" not in st.session_state:
    st.session_state.last_plan = ""
if "last_extracted" not in st.session_state:
    st.session_state.last_extracted = ""
if "last_critique" not in st.session_state:
    st.session_state.last_critique = ""

st.write(
    """
    Multi-agent research system using:
    - Local LLMs via Ollama
    - CrewAI agent orchestration
    - RAG with local embeddings (nomic-embed-text)
    - Persistent memory across sessions
    - A2A communication via task context
    """ 
)

# context
col1, col2 = st.columns([4, 1])

with col1:
    if st.session_state.last_report:
        st.info(f"✓ Previous context loaded: \"{st.session_state.last_query}\"")
    else:
        st.caption("No previous context — first query will start fresh.")

with col2:
    if st.session_state.last_report:
        if st.button("🗑 Clear Memory"):
            clear_memory()
            st.session_state.last_report  = ""
            st.session_state.last_query   = ""
            st.session_state.last_plan    = ""
            st.session_state.last_extracted = ""
            st.session_state.last_critique  = ""
            st.success("Memory cleared.")
            st.rerun()

# query input
query = st.text_input(
    "Enter Research Query",
    placeholder="NVIDIA Blackwell GPU data center deployment 2024"
)

if st.button("Run Research"):

    if not query.strip():
        st.error("Please enter a query.")
        st.stop()

    if needs_clarification(query):
        st.warning(
            """
            Query is too broad.

            Please specify one of:
            - financial analysis
            - partnerships
            - AI products
            - acquisitions
            - competitive landscape
            - technical specifications
            """
        )
        st.stop()

    with st.spinner("Running research crew"):
        try:
            report = run_research_crew(
                query=query,
                previous_report=st.session_state.last_report
            )

            st.session_state.last_report = report
            st.session_state.last_query  = query

            # Save to persistent memory with query label
            save_memory(report, query=query)

        except Exception as e:
            st.error(f"Crew failed: {e}")
            st.stop()

    # per agent output
    with st.expander("Research Plan"):
        st.caption("Tasks generated by the Planner agent")
        st.write(st.session_state.get("last_plan", "Not available"))

    with st.expander("Extracted Findings"):
        st.caption("Facts pulled by the Researcher agent")
        st.write(st.session_state.get("last_extracted", "Not available"))

    with st.expander("Critique"):
        st.caption("Gaps identified by the Critic agent")
        critique = st.session_state.get("last_critique", "")
        if not critique or critique.strip() == "I now can give a great answer":
            st.warning("Critic returned an empty or invalid response.")
        else:
            st.write(critique)

    st.subheader("Final Report")
    st.write(report)

    # memory
    with st.expander("Session Memory (all runs)"):
        memory_data = get_memory()
        for entry in reversed(memory_data):
            st.markdown(f"**{entry.get('timestamp', '')}** — {entry.get('query', '')}")
            st.write(entry.get("content", "")[:300] + "...")
            st.write("---")

    # download
    st.download_button(
        label="Download Report",
        data=report,
        file_name="research_report.txt",
        mime="text/plain"
    )
